# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: memory-usage
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"memoryaverage":{"avg":{"field":"system.memory.usage_percent"}}}}}'


apiVersion: metrics.keptn.sh/v1alpha3
kind: AnalysisValueTemplate
metadata:
  name: memory-usage
  namespace: default
spec:
  provider:
    name: my-elastic-provider
  query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.memory.usage_percent"}}}}'



  query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.memory.usage_percent"}}}}'
