# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: disk-usage
#   namespace: default
# spec:
#   provider:
#     name: my-elastic-provider  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.disk.usage_percent"}}}}'

