# apiVersion: metrics.keptn.sh/v1alpha3
# kind: Analysis
# metadata:
#   name: service-analysis
#   namespace: default
# spec:
#   timeframe:
#     from: "2025-03-01T05:21:22.655Z"
#     to: "2025-03-06T05:21:22.655Z"
#   analysisDefinition:
#     name: analysis-definition

# apiVersion: metrics.keptn.sh/v1
# kind: Analysis
# metadata:
#   name: kibana-analysis
#   namespace: default
# spec:
#   timeframe:
#     from: "2025-03-07T12:00:00Z"
#     to: "2025-03-07T12:25:00Z"
#   args:
#     "field": "system.cpu.load" 
#     "from": "2025-03-07T12:00:00Z"
#     "to": "2025-03-07T12:25:00Z" 
#   analysisDefinition:
#     name: kibana-analysis-definition


apiVersion: metrics.keptn.sh/v1
kind: Analysis
metadata:
  name: kibana-analysis
  namespace: default
spec:
  timeframe:
    from: "2025-03-07T12:00:00Z"
    to: "2025-03-12T12:25:00Z"
  args:
    "from": "2025-03-07T12:00:00Z"
    "to": "2025-03-12T12:25:00Z" 
    "metricPath": "metrics"
    "metricPath1": "metrics1"
  analysisDefinition:
    name: kibana-analysis-definition


# apiVersion: metrics.keptn.sh/v1alpha3
# kind: Analysis
# metadata:
#   name: memory-analysis
# spec:
#   timeframe:
#     from: "2025-03-07T12:00:00Z"
#     to: "2025-03-12T12:25:00Z"
#   args:
#     "from": "2025-03-07T12:00:00Z"
#     "to": "2025-03-12T12:25:00Z" 
#     "metricPath": "metrics"
#   analysisDefinition:
#     name: analysis-definition
#     namespace: default
