# apiVersion: metrics.keptn.sh/v1alpha3
# kind: AnalysisValueTemplate
# metadata:
#   name: cpu-load
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: |
#     {
#       "query": {
#         "range": {
#           "system.cpu.load": {
#             "gte": 18
#           }
#         }
#       }
#     }

# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: cpu-load
#   namespace: default
#   annotations:
#     metricPath: "avg_cpu_load" 
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"avg_cpu_load":{"avg":{"field":"system.cpu.load"}}}}'
   

#  query: '{"bool":{"must":[{"range":{"system.cpu.load":{"gt":20}}}]},"aggs":{"avg_value":{"avg":{"field":"system.cpu.load"}}}}'


#cpu-load
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: cpu-load
#   namespace: default
# spec:
#   provider:
#     name: my-elastic-provider  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.cpu.load"}}}}'


# #memory-usage
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: memory-usage
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.memory.usage_percent"}}}}'



# #disk-usage
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: disk-usage
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.disk.usage_percent"}}}}'


# #network-traffic
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: network-traffic
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"system.network.out_bytes"}}}}'


# #api-failure-rate
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: api-failure-rate
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"script": "(doc[\"kibana.requests.failed\"].value / doc[\"kibana.requests.total\"].value) * 100"}}}}'


# #response-time
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: response-time
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"avg":{"field":"kibana.response_time.avg_ms"}}}}'  



#response-time-p95
# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisValueTemplate
# metadata:
#   name: response-time-p95
#   namespace: default
# spec:
#   provider:
#     name: elastic  
#   query: '{"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"{{.from}}","lte":"{{.to}}"}}}]}},"size":0,"aggs":{"{{.metricPath}}":{"percentiles":{"field":"kibana.response_time.avg_ms","percents":[95]}}}}'   




  