# apiVersion: metrics.keptn.sh/v1alpha3
# kind: AnalysisDefinition
# metadata:
#   name: analysis-definition
#   namespace: default
# spec:
#   objectives:
#     - analysisValueTemplateRef: 
#         name: cpu-load
#       weight: 1
#       keyObjective: true
#       target:
#         failure:
#           greaterThan:
#             fixedValue: 20
#         warning:
#           inRange:
#             lowBound: 18
#             highBound: 20
#   totalScore:
#     passPercentage: 90
#     warningPercentage: 75



# apiVersion: metrics.keptn.sh/v1
# kind: AnalysisDefinition
# metadata:
#   name: kibana-analysis-definition
#   namespace: default
# spec:
#   objectives:
#     - analysisValueTemplateRef:
#         name: cpu-load
#       weight: 1
#       keyObjective: true
#       target:
#         failure:
#           greaterThan:
#             fixedValue: 25
#         warning:
#           inRange:
#             lowBound: 20
#             highBound: 25
#   totalScore:
#     passPercentage: 90
#     warningPercentage: 75



apiVersion: metrics.keptn.sh/v1alpha3
kind: AnalysisDefinition
metadata:
  name: kibana-analysis-definition
  namespace: default
spec:
  objectives:
    # - analysisValueTemplateRef:
    #     name: cpu-load
    #   weight: 10
    #   keyObjective: true
    #   target:
    #     failure:
    #       greaterThan:
    #         fixedValue: 40
    #     warning:
    #       inRange:
    #         lowBound: 33
    #         highBound: 39

    - analysisValueTemplateRef:
        name: memory-usage
        namespace: default
      weight: 1
      keyObjective: true
      target:
        failure:
          greaterThan:
            fixedValue: 80
        warning:
          inRange:
            lowBound: 70
            highBound: 80

    # - analysisValueTemplateRef:
    #     name: disk-usage
    #   weight: 1
    #   keyObjective: true
    #   target:
    #     failure:
    #       greaterThan:
    #         fixedValue: 75
    #     warning:
    #       inRange:
    #         lowBound: 60
    #         highBound: 75

    # - analysisValueTemplateRef:
    #     name: network-traffic
    #   weight: 1
    #   keyObjective: true
    #   target:
    #     failure:
    #       greaterThan:
    #         fixedValue: 3000000000  
    #     warning:
    #       inRange:
    #         lowBound: 2000000000    
    #         highBound: 3000000000   

    # - analysisValueTemplateRef:
    #     name: api-failure-rate
    #   weight: 1
    #   keyObjective: true
    #   target:
    #     failure:
    #       greaterThan:
    #         fixedValue: 5
    #     warning:
    #       inRange:
    #         lowBound: 2
    #         highBound: 5

    # - analysisValueTemplateRef:
    #     name: response-time
    #   weight: 1
    #   keyObjective: true
    #   target:
    #     failure:
    #       greaterThan:
    #         fixedValue: 300
    #     warning:
    #       inRange:
    #         lowBound: 100
    #         highBound: 300

    # - analysisValueTemplateRef:
    #     name: response-time-p95
    #   weight: 1
    #   keyObjective: true
    #   target:
    #     failure:
    #       greaterThan:
    #         fixedValue: 500
    #     warning:
    #       inRange:
    #         lowBound: 400
    #         highBound: 500

  totalScore:
    passPercentage: 80
    warningPercentage: 55




# apiVersion: metrics.keptn.sh/v1alpha3
# kind: AnalysisDefinition
# metadata:
#   name: kibana-analysis-definition
#   namespace: default
# spec:
#   objectives:
#     - analysisValueTemplateRef:
#         name: memory-usage
#         namespace: default
#       weight: 1
#       keyObjective: true
#       target:
#         failure:
#           greaterThan:
#             fixedValue: 80
#         warning:
#           inRange:
#             lowBound: 70
#             highBound: 80
#   totalScore:
#     passPercentage: 80
#     warningPercentage: 75



# apiVersion: metrics.keptn.sh/v1alpha3
# kind: AnalysisDefinition
# metadata:
#   name: analysis-definition
#   namespace: default
# spec:
#   objectives:
#     - analysisValueTemplateRef:
#         name: memory-usage
#         namespace: default
#       target:
#         failure:
#           lessThan:
#             fixedValue: 70
#         warning:
#           inRange:
#             lowBound: 80
#             highBound: 90
#       weight: 1
#       keyObjective: true
#   totalScore:
#     passPercentage: 80
#     warningPercentage: 75    